language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.10'
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: script
  on:
    node: '4.1'
    branch: '*'
  script: scripts/deploy.sh
